minimumReleaseAge: 4320
savePrefix: ''
strictDepBuilds: true
blockExoticSubdeps: true
trustPolicy: no-downgrade

trustPolicyExclude:
  - 'semver@6.3.1'
  - 'tinyexec@1.2.2'

engineStrict: true
resolutionMode: time-based
strictPeerDependencies: true
verifyDepsBeforeRun: error

packages:
  - packages/*
  - apps/*

allowBuilds:
  esbuild: false

catalogs:
  storybook:
    storybook: 10.6.0
    '@storybook/addon-a11y': 10.6.0
    '@storybook/addon-docs': 10.6.0
    '@storybook/addon-vitest': 10.6.0
    storybook-solidjs-vite: 10.7.2
  tsdown:
    '@tsdown/css': 0.22.5
    tsdown: 0.22.5
  vitest:
    vitest: 4.1.11
    '@vitest/browser-playwright': 4.1.11
    '@vitest/coverage-istanbul': 4.1.11
    '@vitest/coverage-v8': 4.1.11
  vite:
    vite: 8.1.5
    '@solidjs/vite-plugin': 3.0.0-next.41
  solid:
    solid-js: 2.0.0-rc.8
    '@solidjs/web': 2.0.0-rc.8
    '@solidjs/router': 2.0.0-next.23
    '@solidjs/meta': 1.0.0-next.2
  primitives:
    '@solid-primitives/active-element': 3.0.0-next.2
    '@solid-primitives/focus': 1.0.0-next.4
    '@solid-primitives/interaction': 1.0.0-next.4
    '@solid-primitives/intersection-observer': 3.0.0-next.3
    '@solid-primitives/media': 4.0.0-next.2
    '@solid-primitives/mutation-observer': 3.0.0-next.2
    '@solid-primitives/pointer': 1.0.0-next.2
    '@solid-primitives/refs': 3.0.0-next.2
    '@solid-primitives/resize-observer': 4.0.0-next.3
    '@solid-primitives/scheduled': 2.0.0-next.2
    '@solid-primitives/storage': 5.0.0-next.4
    '@solid-primitives/transition-group': 2.0.0-next.2
  testing:
    '@solidjs/testing-library': 1.0.0-beta.3
    playwright: 1.59.1

versioning:
  changelog:
    storage: repository
